解决构建错误
+ chown -R kdev:kdev
chown: missing operand after ‘kdev:kdev’
Try 'chown --help' for more information.
Error: Process completed with exit code 1.

Signed-off-by: yifengyou <842056007@qq.com>